package se.yverling.lab.android.design.theme

import androidx.compose.ui.graphics.Color

// Generated from Material Theme Builder Figma plugin
internal val md_theme_light_primary = Color(0xFF00687B)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFAEECFF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001F26)
internal val md_theme_light_secondary = Color(0xFF4B6269)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFCEE7EF)
internal val md_theme_light_onSecondaryContainer = Color(0xFF061F25)
internal val md_theme_light_tertiary = Color(0xFF575C7E)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFDEE0FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF141937)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_outline = Color(0xFF70787C)
internal val md_theme_light_background = Color(0xFFFBFCFE)
internal val md_theme_light_onBackground = Color(0xFF191C1D)
internal val md_theme_light_surface = Color(0xFFF8F9FB)
internal val md_theme_light_onSurface = Color(0xFF191C1D)
internal val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
internal val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)
internal val md_theme_light_inverseSurface = Color(0xFF2E3132)
internal val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
internal val md_theme_light_inversePrimary = Color(0xFF57D6F6)
internal val md_theme_light_surfaceTint = Color(0xFF00687B)
internal val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF57D6F6)
internal val md_theme_dark_onPrimary = Color(0xFF003641)
internal val md_theme_dark_primaryContainer = Color(0xFF004E5D)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFAEECFF)
internal val md_theme_dark_secondary = Color(0xFFB2CBD3)
internal val md_theme_dark_onSecondary = Color(0xFF1D343A)
internal val md_theme_dark_secondaryContainer = Color(0xFF344A51)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFCEE7EF)
internal val md_theme_dark_tertiary = Color(0xFFC0C4EB)
internal val md_theme_dark_onTertiary = Color(0xFF292E4D)
internal val md_theme_dark_tertiaryContainer = Color(0xFF404565)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFDEE0FF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_outline = Color(0xFF899295)
internal val md_theme_dark_background = Color(0xFF191C1D)
internal val md_theme_dark_onBackground = Color(0xFFE1E3E4)
internal val md_theme_dark_surface = Color(0xFF111415)
internal val md_theme_dark_onSurface = Color(0xFFC5C7C8)
internal val md_theme_dark_surfaceVariant = Color(0xFF3F484B)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
internal val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
internal val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
internal val md_theme_dark_inversePrimary = Color(0xFF00687B)
internal val md_theme_dark_surfaceTint = Color(0xFF57D6F6)
internal val md_theme_dark_outlineVariant = Color(0xFF3F484B)
internal val md_theme_dark_scrim = Color(0xFF000000)

internal val seed = Color(0xFF4F99AD)
